### ISSUE TITLE
TinyMCE 3.5.11 support?

### ISSUE THREAD

**Issue by Juuro** [aguvillalba/improvedcode#3]
Hi!

Does your plugin support TinyMCE version 3.5.11? I always geht this error in Firefox ESR 38.2.0:

```
HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy
rng.insertNode(rng.createContextualFragment(content));
```
in tiny_mce_jquery_src.js line 8270

**Comment by aguvillalba** [comment]
Hi Juuro,

Yes, the plugin works with TinyMCE 3.5.11. Actually, I am not able to reproduce the issue you mentioned. I tried in FF 40.0.3 with TinyMCE jQuery package and it works fine. Could you give more hints?

Cheers!
