### ISSUE TITLE
Preformatted text

### ISSUE THREAD

**Issue by ignaciogros** [aguvillalba/improvedcode#4]
Hi, Agustín.

CodeMirror changes the preformatted text (what's inside PRE tags). Example:

<div class="pre-code">
<div>
<pre><code>&lt;div class="pre-code"&gt;
&lt;div&gt;
&lt;pre&gt;&lt;code&gt;function testing(){
    alert("Hi!");
}&lt;/code&gt;&lt;/pre&gt;
&lt;/div&gt;
&lt;/div&gt;</code></pre>
</div>
</div>

And a request: Search/Replace options.

Nice plugin!

Thanks a lot,

Ignacio

**Comment by aguvillalba** [comment]
Hi Ignacio,

I am not able to reproduce your problem. What is exactly your issue?

Cheers!

**Comment by ignaciogros** [comment]
Hi, Agustín.

Using TinyMCE 3:

* Paste that code using TinyMCE's HTML button.
* Update it with your plugin (without changing anything).

The presentation changes, because what's inside the CODE tag is different (that code's beautified, but it shouldn't be touched at all).

Thanks.

**Comment by aguvillalba** [comment]
Hi Ignacio,

Thank you for pointing this out. This issue is solved in the new release (v 1.3.1).

Cheers!
Agustin.

**Comment by ignaciogros** [comment]
Hi Agustín.

Thank you!
